#
# This source file is part of the SpeziNotifications open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  workflow_call:

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordSpezi/.github/.github/workflows/reuse.yml@v2
  swiftlint:
    name: SwiftLint
    uses: StanfordSpezi/.github/.github/workflows/swiftlint.yml@v2
  packageios:
    name: Build and Test Swift Package iOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziNotifications
      resultBundle: SpeziNotifications-iOS.xcresult
      artifactname: SpeziNotifications-iOS.xcresult
  packagewatchos:
    name: Build and Test Swift Package watchOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziNotifications
      destination: 'platform=watchOS Simulator,name=Apple Watch Series 10 (46mm)'
      resultBundle: SpeziNotifications-watchOS.xcresult
      artifactname: SpeziNotifications-watchOS.xcresult
  packagevisionos:
    name: Build and Test Swift Package visionOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziNotifications
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      resultBundle: SpeziNotifications-visionOS.xcresult
      artifactname: SpeziNotifications-visionOS.xcresult
  packagetvos:
    name: Build and Test Swift Package tvOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziNotifications
      resultBundle: SpeziNotifications-tvOS.xcresult
      destination: 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation)'
      artifactname: SpeziNotifications-tvOS.xcresult
  packagemacos:
    name: Build and Test Swift Package macOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziNotifications
      resultBundle: SpeziNotifications-macOS.xcresult
      destination: 'platform=macOS,arch=arm64'
      artifactname: SpeziNotifications-macOS.xcresult
  ios:
    name: Build and Test iOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      path: 'Tests/UITests'
      scheme: TestApp
      resultBundle: TestApp-iOS.xcresult
      artifactname: TestApp-iOS.xcresult
  ipados:
    name: Build and Test iPadOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      path: 'Tests/UITests'
      scheme: TestApp
      destination: 'platform=iOS Simulator,name=iPad Air 13-inch (M2)'
      resultBundle: TestApp-iPadOS.xcresult
      artifactname: TestApp-iPadOS.xcresult
  watchos:
    name: Build and Test watchOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestAppWatchApp
      destination: 'platform=watchOS Simulator,name=Apple Watch Series 10 (46mm)'
      resultBundle: TestApp-watchOS.xcresult
      artifactname: TestApp-watchOS.xcresult
  visionos:
    name: Build and Test visionOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestApp
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      resultBundle: TestApp-visionOS.xcresult
      artifactname: TestApp-visionOS.xcresult
  tvos:
    name: Build and Test tvOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      path: 'Tests/UITests'
      scheme: TestApp
      destination: 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation)'
      resultBundle: TestApp-tvOS.xcresult
      artifactname: TestApp-tvOS.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [packageios, packagewatchos, packagevisionos, packagetvos, packagemacos, ios, ipados, watchos, visionos, tvos]
    uses: StanfordSpezi/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: SpeziNotifications-iOS.xcresult SpeziNotifications-watchOS.xcresult SpeziNotifications-visionOS.xcresult SpeziNotifications-tvOS.xcresult SpeziNotifications-macOS.xcresult TestApp-iOS.xcresult TestApp-iPadOS.xcresult TestApp-watchOS.xcresult TestApp-visionOS.xcresult TestApp-tvOS.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
